name: Java CI

on: [push]

jobs:
  init:
    runs-on: ubuntu-latest

    steps:
      - name: Echoing sth
        run: echo "Build is starting!!!"
  build:
    needs: init
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots -DskipTests clean package
      - name: Move war to staging 
        run: mkdir staging && cp book-rest/target/*.war staging
      - name: Uploading war file
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Test with Maven
        run: mvn verify -P tomcat8x
      - name: Move test results to results 
        run: mkdir results && cp book-functional-tests/target/failsafe-reports/*.xml results
      - name: Uploading test results
        uses: actions/upload-artifact@v2
        with:
          name: Test-Result
          path: results
